spring.application.name=licorera-jm-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/licorera_jm
spring.datasource.username=postgres
spring.datasource.password=${LICORERA_JM_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${LICORERA_JM_JWT_SECRET}
security.jwt.expiration=86400000

app.backup.directory=backups
app.backup.cron=0 0 18 * * *
