spring.application.name=licorera-jm-backend

# ========================================
# CONEXIÓN A POSTGRESQL
# ========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/licorera_jm
spring.datasource.username=postgres
spring.datasource.password=REDACTED

# ========================================
# JPA / HIBERNATE
# ========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
security.jwt.secret=***REMOVED***
security.jwt.expiration=86400000